In [37]:
import boto3
import pandas as pd
import io
from clickhouse_driver import Client
from typing import Optional
from tqdm import tqdm

In [99]:

s3 = boto3.client('s3')
bucket = 'databricks-binance-pipeline'

# List all parquet files
paginator = s3.get_paginator('list_objects_v2')
files = []
for page in paginator.paginate(Bucket=bucket):
    for obj in page.get('Contents', []):
        if obj['Key'].endswith('.parquet'):
            files.append(obj['Key'])

print(f'Total files found: {len(files)}')
# for f in files:
#     print(f)

# Load all into one dataframe
dfs = []
btc = []
eth = []
for file_key in tqdm(files):
    print(file_key)
    if "ETH" in file_key:
        obj = s3.get_object(Bucket=bucket, Key=file_key)
        df = pd.read_parquet(io.BytesIO(obj['Body'].read()))
        eth.append(df)
    if "BTC" in file_key:
        obj = s3.get_object(Bucket=bucket, Key=file_key)
        df = pd.read_parquet(io.BytesIO(obj['Body'].read()))
        btc.append(df)

btc_df = pd.concat(btc, ignore_index=True)
eth_df = pd.concat(eth, ignore_index=True)
# combined_df = pd.concat(dfs, ignore_index=True)
# print(f'Total rows: {len(combined_df)}')
# print(f'Columns: {combined_df.columns.tolist()}')
# print(combined_df.head(3))

Total files found: 66

  0%|          | 0/66 [00:00<?, ?it/s]

BTCUSDT/2026-01-01/BTCUSDT_1767229199980.parquet

  2%|▏         | 1/66 [00:01<01:13,  1.13s/it]

BTCUSDT/2026-01-01/BTCUSDT_1767232799258.parquet

  3%|▎         | 2/66 [00:01<00:53,  1.19it/s]

BTCUSDT/2026-01-01/BTCUSDT_1767236399843.parquet

  5%|▍         | 3/66 [00:02<00:40,  1.56it/s]

BTCUSDT/2026-01-01/BTCUSDT_1767239999981.parquet

  6%|▌         | 4/66 [00:02<00:34,  1.81it/s]

BTCUSDT/2026-01-01/BTCUSDT_1767243599599.parquet

  8%|▊         | 5/66 [00:03<00:40,  1.51it/s]

BTCUSDT/2026-01-01/BTCUSDT_1767247199752.parquet

  9%|▉         | 6/66 [00:03<00:36,  1.65it/s]

BTCUSDT/2026-01-01/BTCUSDT_1767250799885.parquet

 11%|█         | 7/66 [00:04<00:37,  1.59it/s]

BTCUSDT/2026-01-01/BTCUSDT_1767254399132.parquet

 12%|█▏        | 8/66 [00:05<00:33,  1.76it/s]

BTCUSDT/2026-01-01/BTCUSDT_1767257999878.parquet

 14%|█▎        | 9/66 [00:05<00:33,  1.72it/s]

BTCUSDT/2026-01-01/BTCUSDT_1767261599336.parquet

 15%|█▌        | 10/66 [00:06<00:28,  1.97it/s]

BTCUSDT/2026-01-01/BTCUSDT_1767265199276.parquet

 17%|█▋        | 11/66 [00:06<00:27,  2.03it/s]

BTCUSDT/2026-01-01/BTCUSDT_1767268798403.parquet

 18%|█▊        | 12/66 [00:06<00:24,  2.19it/s]

BTCUSDT/2026-01-01/BTCUSDT_1767272398596.parquet

 20%|█▉        | 13/66 [00:07<00:22,  2.36it/s]

BTCUSDT/2026-01-01/BTCUSDT_1767275999882.parquet

 21%|██        | 14/66 [00:09<00:51,  1.01it/s]

BTCUSDT/2026-01-01/BTCUSDT_1767279599841.parquet

 23%|██▎       | 15/66 [00:11<01:09,  1.35s/it]

BTCUSDT/2026-01-01/BTCUSDT_1767283199857.parquet

 24%|██▍       | 16/66 [00:12<00:56,  1.13s/it]

BTCUSDT/2026-01-01/BTCUSDT_1767286798976.parquet

 26%|██▌       | 17/66 [00:12<00:47,  1.02it/s]

BTCUSDT/2026-01-01/BTCUSDT_1767290400001.parquet

 27%|██▋       | 18/66 [00:13<00:45,  1.06it/s]

BTCUSDT/2026-01-01/BTCUSDT_1767293998459.parquet

 29%|██▉       | 19/66 [00:14<00:41,  1.12it/s]

BTCUSDT/2026-01-01/BTCUSDT_1767297599387.parquet

 30%|███       | 20/66 [00:15<00:37,  1.23it/s]

BTCUSDT/2026-01-01/BTCUSDT_1767301199629.parquet

 32%|███▏      | 21/66 [00:15<00:33,  1.36it/s]

BTCUSDT/2026-01-01/BTCUSDT_1767304799859.parquet

 33%|███▎      | 22/66 [00:16<00:30,  1.45it/s]

BTCUSDT/2026-01-01/BTCUSDT_1767308398982.parquet

 35%|███▍      | 23/66 [00:16<00:28,  1.50it/s]

BTCUSDT/2026-01-01/BTCUSDT_1767311999601.parquet

 36%|███▋      | 24/66 [00:17<00:27,  1.54it/s]

BTCUSDT/2026-01-02/BTCUSDT_1767315598672.parquet

 38%|███▊      | 25/66 [00:18<00:25,  1.59it/s]

BTCUSDT/2026-01-02/BTCUSDT_1767319198999.parquet

 39%|███▉      | 26/66 [00:18<00:26,  1.51it/s]

BTCUSDT/2026-01-02/BTCUSDT_1767322799682.parquet

 41%|████      | 27/66 [00:19<00:25,  1.53it/s]

BTCUSDT/2026-01-02/BTCUSDT_1767326399945.parquet

 42%|████▏     | 28/66 [00:20<00:30,  1.27it/s]

BTCUSDT/2026-01-02/BTCUSDT_1767329999718.parquet

 44%|████▍     | 29/66 [00:21<00:29,  1.23it/s]

BTCUSDT/2026-01-02/BTCUSDT_1767333598310.parquet

 45%|████▌     | 30/66 [00:22<00:28,  1.27it/s]

BTCUSDT/2026-01-02/BTCUSDT_1767337199349.parquet

 47%|████▋     | 31/66 [00:22<00:26,  1.33it/s]

BTCUSDT/2026-01-02/BTCUSDT_1767340799810.parquet

 48%|████▊     | 32/66 [00:23<00:24,  1.40it/s]

BTCUSDT/2026-01-02/BTCUSDT_1767344399969.parquet

 50%|█████     | 33/66 [00:24<00:26,  1.25it/s]

ETHUSDT/2026-01-01/ETHUSDT_1767229197059.parquet

 52%|█████▏    | 34/66 [00:24<00:21,  1.51it/s]

ETHUSDT/2026-01-01/ETHUSDT_1767232799751.parquet

 53%|█████▎    | 35/66 [00:25<00:17,  1.78it/s]

ETHUSDT/2026-01-01/ETHUSDT_1767236399872.parquet

 55%|█████▍    | 36/66 [00:25<00:14,  2.00it/s]

ETHUSDT/2026-01-01/ETHUSDT_1767239999735.parquet

 56%|█████▌    | 37/66 [00:25<00:13,  2.22it/s]

ETHUSDT/2026-01-01/ETHUSDT_1767243598925.parquet

 58%|█████▊    | 38/66 [00:26<00:12,  2.32it/s]

ETHUSDT/2026-01-01/ETHUSDT_1767247199406.parquet

 59%|█████▉    | 39/66 [00:26<00:11,  2.34it/s]

ETHUSDT/2026-01-01/ETHUSDT_1767250799402.parquet

 61%|██████    | 40/66 [00:26<00:10,  2.48it/s]

ETHUSDT/2026-01-01/ETHUSDT_1767254399347.parquet

 62%|██████▏   | 41/66 [00:27<00:09,  2.58it/s]

ETHUSDT/2026-01-01/ETHUSDT_1767257999851.parquet

 64%|██████▎   | 42/66 [00:27<00:09,  2.53it/s]

ETHUSDT/2026-01-01/ETHUSDT_1767261598981.parquet

 65%|██████▌   | 43/66 [00:28<00:09,  2.48it/s]

ETHUSDT/2026-01-01/ETHUSDT_1767265199659.parquet

 67%|██████▋   | 44/66 [00:28<00:08,  2.62it/s]

ETHUSDT/2026-01-01/ETHUSDT_1767268799959.parquet

 68%|██████▊   | 45/66 [00:28<00:07,  2.69it/s]

ETHUSDT/2026-01-01/ETHUSDT_1767272398109.parquet

 70%|██████▉   | 46/66 [00:32<00:25,  1.28s/it]

ETHUSDT/2026-01-01/ETHUSDT_1767275999304.parquet

 71%|███████   | 47/66 [00:33<00:23,  1.23s/it]

ETHUSDT/2026-01-01/ETHUSDT_1767279598751.parquet

 73%|███████▎  | 48/66 [00:34<00:20,  1.12s/it]

ETHUSDT/2026-01-01/ETHUSDT_1767283198374.parquet

 74%|███████▍  | 49/66 [00:34<00:16,  1.01it/s]

ETHUSDT/2026-01-01/ETHUSDT_1767286799365.parquet

 76%|███████▌  | 50/66 [00:35<00:14,  1.13it/s]

ETHUSDT/2026-01-01/ETHUSDT_1767290397009.parquet

 77%|███████▋  | 51/66 [00:36<00:13,  1.12it/s]

ETHUSDT/2026-01-01/ETHUSDT_1767293997690.parquet

 79%|███████▉  | 52/66 [00:37<00:11,  1.22it/s]

ETHUSDT/2026-01-01/ETHUSDT_1767297599753.parquet

 80%|████████  | 53/66 [00:37<00:09,  1.43it/s]

ETHUSDT/2026-01-01/ETHUSDT_1767301198027.parquet

 82%|████████▏ | 54/66 [00:37<00:07,  1.66it/s]

ETHUSDT/2026-01-01/ETHUSDT_1767304799675.parquet

 83%|████████▎ | 55/66 [00:38<00:05,  1.91it/s]

ETHUSDT/2026-01-01/ETHUSDT_1767308397629.parquet

 85%|████████▍ | 56/66 [00:38<00:04,  2.14it/s]

ETHUSDT/2026-01-01/ETHUSDT_1767311998721.parquet

 86%|████████▋ | 57/66 [00:39<00:04,  1.86it/s]

ETHUSDT/2026-01-02/ETHUSDT_1767315599737.parquet

 88%|████████▊ | 58/66 [00:40<00:04,  1.65it/s]

ETHUSDT/2026-01-02/ETHUSDT_1767319199086.parquet

 89%|████████▉ | 59/66 [00:40<00:03,  1.92it/s]

ETHUSDT/2026-01-02/ETHUSDT_1767322799948.parquet

 91%|█████████ | 60/66 [00:40<00:03,  1.99it/s]

ETHUSDT/2026-01-02/ETHUSDT_1767326399328.parquet

 92%|█████████▏| 61/66 [00:41<00:03,  1.45it/s]

ETHUSDT/2026-01-02/ETHUSDT_1767329999881.parquet

 94%|█████████▍| 62/66 [00:42<00:02,  1.53it/s]

ETHUSDT/2026-01-02/ETHUSDT_1767333599439.parquet

 95%|█████████▌| 63/66 [00:42<00:01,  1.72it/s]

ETHUSDT/2026-01-02/ETHUSDT_1767337199612.parquet

 97%|█████████▋| 64/66 [00:43<00:01,  1.60it/s]

ETHUSDT/2026-01-02/ETHUSDT_1767340798270.parquet

 98%|█████████▊| 65/66 [00:44<00:00,  1.63it/s]

ETHUSDT/2026-01-02/ETHUSDT_1767344398582.parquet

100%|██████████| 66/66 [00:44<00:00,  1.47it/s]

In [100]:
btc_df

,trade_id,price,quantity,first_trade_id,last_trade_id,timestamp_utc,is_maker,best_match,datetime
0,3800397495,87648.21,0.08185,5723703861,5723703861,1767225600039,True,True,2026-01-01 00:00:00.039
1,3800397496,87648.22,0.00013,5723703862,5723703862,1767225600272,False,True,2026-01-01 00:00:00.272
2,3800397497,87648.22,0.00023,5723703863,5723703863,1767225600276,False,True,2026-01-01 00:00:00.276
3,3800397498,87648.22,0.01032,5723703864,5723703864,1767225600396,False,True,2026-01-01 00:00:00.396
4,3800397499,87648.22,0.00206,5723703865,5723703865,1767225600401,False,True,2026-01-01 00:00:00.401
...,...,...,...,...,...,...,...,...,...
616342,3801013837,89178.14,0.00176,5726020222,5726020222,1767344399305,False,True,2026-01-02 08:59:59.305
616343,3801013838,89178.14,0.00013,5726020223,5726020223,1767344399597,False,True,2026-01-02 08:59:59.597
616344,3801013839,89178.14,0.00013,5726020224,5726020224,1767344399597,False,True,2026-01-02 08:59:59.597
616345,3801013840,89178.14,0.00014,5726020225,5726020225,1767344399623,False,True,2026-01-02 08:59:59.623
616346,3801013841,89178.13,0.00454,5726020226,5726020229,1767344399969,True,True,2026-01-02 08:59:59.969

In [101]:
eth_df

,trade_id,price,quantity,first_trade_id,last_trade_id,timestamp_utc,is_maker,best_match,datetime
0,1850031664,2971.65,0.5435,3402303373,3402303374,1767225601317,False,True,2026-01-01 00:00:01.317
1,1850031665,2971.65,0.0134,3402303375,3402303375,1767225601512,False,True,2026-01-01 00:00:01.512
2,1850031666,2971.65,0.0033,3402303376,3402303376,1767225601694,False,True,2026-01-01 00:00:01.694
3,1850031667,2971.64,0.2401,3402303377,3402303377,1767225601706,True,True,2026-01-01 00:00:01.706
4,1850031668,2971.65,22.3538,3402303378,3402303429,1767225601798,False,True,2026-01-01 00:00:01.798
...,...,...,...,...,...,...,...,...,...
425054,1850456718,3032.28,0.0329,3404621944,3404621956,1767344394906,False,True,2026-01-02 08:59:54.906
425055,1850456719,3032.28,0.0330,3404621957,3404621959,1767344396059,False,True,2026-01-02 08:59:56.059
425056,1850456720,3032.28,0.0633,3404621960,3404621960,1767344396928,False,True,2026-01-02 08:59:56.928
425057,1850456721,3032.27,0.0074,3404621961,3404621961,1767344397034,True,True,2026-01-02 08:59:57.034
425058,1850456722,3032.28,0.0605,3404621962,3404621966,1767344398582,False,True,2026-01-02 08:59:58.582

In [107]:
import os
from dotenv import load_dotenv

# This looks for a file named .env in the same directory and loads it
load_dotenv()

True

In [ ]:
# ── Config ────────────────────────────────────────────────
BUCKET          = 'databricks-binance-pipeline'
PREFIX          = 'BTCUSDT/'
CLICKHOUSE_HOST = os.getenv("CLICKHOUSE_HOST")
CLICKHOUSE_PORT = os.getenv("CLICKHOUSE_PORT")
CLICKHOUSE_USER = os.getenv("CLICKHOUSE_USER")
CLICKHOUSE_PASS = os.getenv("CLICKHOUSE_PASS")
CLICKHOUSE_DB   = os.getenv("CLICKHOUSE_DB")
CLICKHOUSE_TABLE= 'btcusdt_trades'
BATCH_SIZE      = 50000
# ──────────────────────────────────────────────────────────
# print(CLICKHOUSE_HOST)
d

In [111]:
from clickhouse_connect import get_client

client = get_client(
    host=CLICKHOUSE_HOST,
    port=CLICKHOUSE_PORT,
    username=CLICKHOUSE_USER,
    password=CLICKHOUSE_PASS,
    database=CLICKHOUSE_DB
)

In [112]:
print(client.command("SELECT 1"))

1

In [113]:


def prepare_df(df):
    df = df.copy()

    df['datetime']       = pd.to_datetime(df['datetime'], errors='coerce')
    df['is_maker']       = df['is_maker'].astype(bool)
    df['best_match']     = df['best_match'].astype(bool)
    df['trade_id']       = pd.to_numeric(df['trade_id'], errors='coerce')
    df['first_trade_id'] = pd.to_numeric(df['first_trade_id'], errors='coerce')
    df['last_trade_id']  = pd.to_numeric(df['last_trade_id'], errors='coerce')
    df['timestamp_utc']  = pd.to_numeric(df['timestamp_utc'], errors='coerce')
    df['price']          = pd.to_numeric(df['price'], errors='coerce')
    df['quantity']       = pd.to_numeric(df['quantity'], errors='coerce')

    # drop bad rows (important!)
    df = df.dropna()

    return df

,trade_id,price,quantity,first_trade_id,last_trade_id,timestamp_utc,is_maker,best_match,datetime
0,1850438887,3018.32,0.0084,3404524849,3404524849,1767340800240,True,True,2026-01-02 08:00:00.240
1,1850438888,3018.32,0.0315,3404524850,3404524850,1767340800338,True,True,2026-01-02 08:00:00.338
2,1850438889,3018.32,0.0256,3404524851,3404524851,1767340800368,True,True,2026-01-02 08:00:00.368
3,1850438890,3018.32,0.0054,3404524852,3404524852,1767340800428,True,True,2026-01-02 08:00:00.428
4,1850438891,3018.33,0.0033,3404524853,3404524853,1767340800758,False,True,2026-01-02 08:00:00.758
...,...,...,...,...,...,...,...,...,...
17831,1850456718,3032.28,0.0329,3404621944,3404621956,1767344394906,False,True,2026-01-02 08:59:54.906
17832,1850456719,3032.28,0.0330,3404621957,3404621959,1767344396059,False,True,2026-01-02 08:59:56.059
17833,1850456720,3032.28,0.0633,3404621960,3404621960,1767344396928,False,True,2026-01-02 08:59:56.928
17834,1850456721,3032.27,0.0074,3404621961,3404621961,1767344397034,True,True,2026-01-02 08:59:57.034
17835,1850456722,3032.28,0.0605,3404621962,3404621966,1767344398582,False,True,2026-01-02 08:59:58.582

In [40]:
combined_df

,trade_id,price,quantity,first_trade_id,last_trade_id,timestamp_utc,is_maker,best_match,datetime
0,3800397495,87648.21,0.08185,5723703861,5723703861,1767225600039,True,True,2026-01-01 00:00:00.039
1,3800397496,87648.22,0.00013,5723703862,5723703862,1767225600272,False,True,2026-01-01 00:00:00.272
2,3800397497,87648.22,0.00023,5723703863,5723703863,1767225600276,False,True,2026-01-01 00:00:00.276
3,3800397498,87648.22,0.01032,5723703864,5723703864,1767225600396,False,True,2026-01-01 00:00:00.396
4,3800397499,87648.22,0.00206,5723703865,5723703865,1767225600401,False,True,2026-01-01 00:00:00.401
...,...,...,...,...,...,...,...,...,...
1041401,1850456718,3032.28,0.03290,3404621944,3404621956,1767344394906,False,True,2026-01-02 08:59:54.906
1041402,1850456719,3032.28,0.03300,3404621957,3404621959,1767344396059,False,True,2026-01-02 08:59:56.059
1041403,1850456720,3032.28,0.06330,3404621960,3404621960,1767344396928,False,True,2026-01-02 08:59:56.928
1041404,1850456721,3032.27,0.00740,3404621961,3404621961,1767344397034,True,True,2026-01-02 08:59:57.034
1041405,1850456722,3032.28,0.06050,3404621962,3404621966,1767344398582,False,True,2026-01-02 08:59:58.582

1

In [94]:
test = prepare_df(combined_df.iloc[:10000
                                   ].reset_index(drop=True))
test

,trade_id,price,quantity,first_trade_id,last_trade_id,timestamp_utc,is_maker,best_match,datetime
0,3800397495,87648.21,0.08185,5723703861,5723703861,1767225600039,True,True,2026-01-01 00:00:00.039
1,3800397496,87648.22,0.00013,5723703862,5723703862,1767225600272,False,True,2026-01-01 00:00:00.272
2,3800397497,87648.22,0.00023,5723703863,5723703863,1767225600276,False,True,2026-01-01 00:00:00.276
3,3800397498,87648.22,0.01032,5723703864,5723703864,1767225600396,False,True,2026-01-01 00:00:00.396
4,3800397499,87648.22,0.00206,5723703865,5723703865,1767225600401,False,True,2026-01-01 00:00:00.401
...,...,...,...,...,...,...,...,...,...
9995,3800407490,87748.08,0.00460,5723732885,5723732890,1767228001778,True,True,2026-01-01 00:40:01.778
9996,3800407491,87748.07,0.00027,5723732891,5723732893,1767228001778,True,True,2026-01-01 00:40:01.778
9997,3800407492,87747.88,0.00018,5723732894,5723732896,1767228001779,True,True,2026-01-01 00:40:01.779
9998,3800407493,87747.87,0.04052,5723732897,5723732897,1767228001779,True,True,2026-01-01 00:40:01.779
9999,3800407494,87747.87,0.03034,5723732898,5723732898,1767228001782,True,True,2026-01-01 00:40:01.782

In [103]:
# for i in range (len(test)):
#     client.query(f"""INSERT INTO btcusdt_trades (trade_id,price,quantity,first_trade_id,last_trade_id,timestamp_utc,is_maker,best_match,datetime) 
#              VALUES ({test["trade_id"][i]},
#                     {test["price"][i]},
#                     {test["quantity"][i]},
#                     {test["first_trade_id"][i]},
#                     {test["last_trade_id"][i]},
#                     {test["timestamp_utc"][i]},
#                     {test["is_maker"][i]},
#                     {test["best_match"][i]},
#                     toDateTime64('{test["datetime"][i]}', 6, 'UTC')
#                     ); """)
client.insert('ethusdt_trades', prepare_df(eth_df), column_names=[
    'trade_id', 'price', 'quantity', 'first_trade_id', 
    'last_trade_id', 'timestamp_utc', 'is_maker', 'best_match', 'datetime'
])

In [76]:
for col in test.columns:
    print(f"test[\"{col}\"][i],")

test["trade_id"][i],
test["price"][i],
test["quantity"][i],
test["first_trade_id"][i],
test["last_trade_id"][i],
test["timestamp_utc"][i],
test["is_maker"][i],
test["best_match"][i],
test["datetime"][i],

In [78]:
test["trade_id"][0]

3800397495

In [79]:
test.dtypes

trade_id            int64
price             float64
quantity          float64
first_trade_id      int64
last_trade_id       int64
timestamp_utc       int64
is_maker             bool
best_match           bool
datetime           object
dtype: object